ARG ARCH
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.5-buster-slim-${ARCH} AS build

ARG IMGPATH

WORKDIR /app

COPY Vecc.AzSync/bin/Release/net5.0/${IMGPATH}/publish/Vecc.AzSync /app

RUN chmod +x ./Vecc.AzSync

ENTRYPOINT [ "./Vecc.AzSync" ]

#------------------

ARG ARCH
FROM mcr.microsoft.com/dotnet/runtime-deps:5.0.5-buster-slim-${ARCH}
WORKDIR /app
COPY --from=build /app /app
ENTRYPOINT [ "./Vecc.AzSync" ]